### ISSUE TITLE
set.seed for simulateSEM function

### ISSUE THREAD

**Issue by felixthoemmes** [jtextor/dagitty#12]
To increase reproducibility, it would be good to have a set.seed() function for simulateSEM, like

dat1 <- simulateSEM(dag1,b.default = .3,N=500,set.seed=1234)

That way, one could always generate the same (simulated) data, across different runs of R code.

**Comment by jtextor** [comment]
Not sure I understand this, what is wrong with simply calling "set.seed" before running simulateSEM?

**Comment by felixthoemmes** [comment]
Not sure I understand either, since it's been a while I posted this, and
TBH I don't recall details. But if just putting set.seed works, then that's
great and the issue can be closed.

**Comment by jtextor** [comment]
Yes this works as you can testify by running the following multiple times:

set.seed(123); with(simulateSEM( "dag{x->y}" ),cov(x,y))

Closing this as having a separate argument seems unnecessary.
