### ISSUE TITLE
Incorrect comments for dconnected and dseparated in documentation

### ISSUE THREAD

**Issue by rer98** [jtextor/dagitty#26]
In the R documentation for dconnected and dseparated methods, the following examples are listed at the end:

"dconnected( "dag{x->m->y}", "x", "y", c() ) # TRUE
dconnected( "dag{x->m->y}", "x", "y", c("m") ) # FALSE
dseparated( "dag{x->m->y}", "x", "y", c() ) # TRUE
dseparated( "dag{x->m->y}", "x", "y", c("m") ) # FALSE"

The comments for the last two (dseparated) lines should be the other way around, as in :

"dseparated( "dag{x->m->y}", "x", "y", c() ) # FALSE
dseparated( "dag{x->m->y}", "x", "y", c("m") ) # TRUE"

**Comment by jtextor** [comment]
Thanks! Fixed in the latest commit.
