### ISSUE TITLE
DAGitty Online v3.0 bug in Generate Layout Automatically

### ISSUE THREAD

**Issue by hbuckley545** [jtextor/dagitty#29]
When choosing the Generate Layout Automatically in DAGitty 3.0 online for a large DAG (~26 variables) all but one variable disappears out of view and I could not move them back within view.

**Comment by jtextor** [comment]
Sorry to hear that. I just tried to reproduce this problem but couldn't . Which browser are you using? Which DAG was that? Do you happen to have a copy of the model text before / after the modification or both?
