### ISSUE TITLE
Finding libplatform.h on Gentoo

### ISSUE THREAD

**Issue by stainesa** [jtextor/dagitty#30]
Hi,
Not sure if this belongs with you or with jeroen. In any event thank you both for very useful software! I suspect the difficulty is not in either package, but you may be able to advise on how to resolve it.

I'm installing dagitty on Gentoo, and there is a working Node.js installation which contains V8. The output is as follows -

`also installing the dependency ‘V8’

trying URL 'https://ftp.heanet.ie/mirrors/cran.r-project.org/src/contrib/V8_2.3.tar.gz'
Content type 'application/x-gzip' length 304765 bytes (297 KB)
==================================================
downloaded 297 KB

trying URL 'https://ftp.heanet.ie/mirrors/cran.r-project.org/src/contrib/dagitty_0.2-2.tar.gz'
Content type 'application/x-gzip' length 168082 bytes (164 KB)
==================================================
downloaded 164 KB

* installing *source* package ‘V8’ ...
** package ‘V8’ successfully unpacked and MD5 sums checked
** using staged installation
Using PKG_CFLAGS=-I/usr/include/v8 -I/usr/include/v8-3.14
Using PKG_LIBS=-lv8 -lv8_libplatform
** libs
rm -f V8.so RcppExports.o bindings.o
x86_64-pc-linux-gnu-g++ -std=gnu++11 -I"/usr/lib64/R/include" -DNDEBUG -I/usr/include/v8 -I/usr/include/v8-3.14 -I"/usr/lib64/R/library/Rcpp/include"  -fvisibility=hidden -fpic  -O2 -pipe  -c RcppExports.cpp -o RcppExports.o
x86_64-pc-linux-gnu-g++ -std=gnu++11 -I"/usr/lib64/R/include" -DNDEBUG -I/usr/include/v8 -I/usr/include/v8-3.14 -I"/usr/lib64/R/library/Rcpp/include"  -fvisibility=hidden -fpic  -O2 -pipe  -c bindings.cpp -o bindings.o
bindings.cpp:1:10: fatal error: libplatform/libplatform.h: No such file or directory
    1 | #include <libplatform/libplatform.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/usr/lib64/R/etc/Makeconf:174: bindings.o] Error 1
ERROR: compilation failed for package ‘V8’
* removing ‘/usr/lib64/R/library/V8’
ERROR: dependency ‘V8’ is not available for package ‘dagitty’
* removing ‘/usr/lib64/R/library/dagitty’

The downloaded source packages are in
        ‘/tmp/RtmpaOhK2w/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages("dagitty") :
  installation of package ‘V8’ had non-zero exit status
2: In install.packages("dagitty") :
  installation of package ‘dagitty’ had non-zero exit status
`

Now, `libplatform.h` is installed at `/usr/include/node/libplatform/libplatform.h` but the R installation can't find it. There are a bunch of other libraries in the same tree.
R does not seem to have a specific configuration for Javascript libraries.

Any suggestions on how to tell R (or gcc) where to find these libraries? I guess it's likely to be the PKG_CFLAGS, but I don't know how to set or alter these.

Any help gratefully received.
Thanks,
Anthony Staines

**Comment by stainesa** [comment]
Ok,
So I tried the following -
R CMD INSTALL --configure-vars='INCLUDE_DIR=/usr/include/node/ LIB_DIR=/usr/local/lib64/libv8_libplatform.so' V8_2.3.tar.gz 

The version of V8 is the package that R downloads. libplatform.so is in /usr/local/lib64 and libplatform/libplatform.h is in /usr/inlcude/node/.

`* installing to library ‘/usr/lib64/R/library’
* installing *source* package ‘V8’ ...
** package ‘V8’ successfully unpacked and MD5 sums checked
** using staged installation
Found INCLUDE_DIR and/or LIB_DIR!
Using PKG_CFLAGS=-I/usr/include/node/ -I/usr/include/v8 -I/usr/include/v8-3.14
Using PKG_LIBS=-L/usr/local/lib64/ -lv8 -lv8_libplatform
** libs
rm -f V8.so RcppExports.o bindings.o
x86_64-pc-linux-gnu-g++ -std=gnu++11 -I"/usr/lib64/R/include" -DNDEBUG -I/usr/include/node/ -I/usr/include/v8 -I/usr/include/v8-3.14 -I"/usr/lib64/R/library/Rcpp/include"  -fvisibility=hidden -fpic  -O2 -pipe  -c RcppExports.cpp -o RcppExports.o
x86_64-pc-linux-gnu-g++ -std=gnu++11 -I"/usr/lib64/R/include" -DNDEBUG -I/usr/include/node/ -I/usr/include/v8 -I/usr/include/v8-3.14 -I"/usr/lib64/R/library/Rcpp/include"  -fvisibility=hidden -fpic  -O2 -pipe  -c bindings.cpp -o bindings.o
x86_64-pc-linux-gnu-g++ -std=gnu++11 -shared -L/usr/lib64/R/lib -Wl,-O1 -Wl,--as-needed -o V8.so RcppExports.o bindings.o -L/usr/local/lib64/ -lv8 -lv8_libplatform -L/usr/lib64/R/lib -lR
installing to /usr/lib64/R/library/00LOCK-V8/00new/V8/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘V8’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/lib64/R/library/00LOCK-V8/00new/V8/libs/V8.so':
  /usr/lib64/R/library/00LOCK-V8/00new/V8/libs/V8.so: undefined symbol: _ZN2v82V818GlobalizeReferenceEPNS_8internal7IsolateEPm
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/lib64/R/library/V8’
`

libplatform.h is part of net-libs/nodejs-12.13.0

What version of nodejs is dagitty looking for?
Regards,
Anthony Staines

**Comment by jtextor** [comment]
Hi Anthony, sorry for not replying earlier. I am not really a gentoo user, but I have seen this issue before on ArchLinux. Unfortunately I can't do much about this as it is the V8 package (which dagitty depends on) that doesn't compile on these platforms. Perhaps you'll have better luck by opening an issue on the V8 GitHub, @jeroen might know how to get this working.
