### ISSUE TITLE
X should (always?) be a parent of Y?

### ISSUE THREAD

**Issue by dholstius** [jtextor/dagitty#36]
Love this package, and the web interface! Thank you so much. I’ve shared it with colleagues. 

While clicking around, I was presented with this challenge. 

![image](https://user-images.githubusercontent.com/825962/82157661-b9707680-9837-11ea-9123-82968f3673f5.png)

It is solvable as far as the question being asked goes. However, it seemed unintuitive to me that X was not depicted an ancestor of Y. Perhaps that relationship should be enforced when a graph is generated? Or, perhaps this is intentional in some way?

**Comment by jtextor** [comment]
This is intentional. There doesn't need to be any relationship between X and Y for there to be a confounder -- in a graphical sense, adding an X->Y arrow to the DAG does not affect the set of confounders at all and this is one of the things this tutorial is meant to emphasize
