### ISSUE TITLE
DAGitty in python?

### ISSUE THREAD

**Issue by elzurdo** [jtextor/dagitty#48]
Excuse the possible blasphemy, 
but is there any initiative to  export code to other languages like python, or even create python modules?

In any case, I'm looking forward to brushing up on my R for the sake of using DAGitty!

**Comment by AndrewC19** [comment]
It's a bit hacky, but you can use the [rpy2 package](https://rpy2.github.io/doc/latest/html/index.html) to run R in python. I currently use this approach to do identification using dagitty and estimation using DoWhy.

**Comment by jtextor** [comment]
I'm fortunate enough to have @ankurankan, who created the pgmpy package, working as a PhD student in my group. He's currently adding some causal inference functions to pgmpy and we'll make the packages interoperable in the not too distant future.

**Comment by AnirbanChakraborty06** [comment]
@jtextor @ankurankan Am not sure if I should be asking this here or in `pgmpy`; pardon me if I am wrong. 

Just wanted to know if the above vision of _interoperability_ between `dagitty` and `pgmpy` has already been achieved? I am particularly interested in graph-specific-functionalities of [`dagitty`](https://cran.r-project.org/web/packages/dagitty/dagitty.pdf) like -

- `impliedConditionalIndependencies`: providing the list of all implied conditional independencies in a DAG
- `paths`: list of biasing paths open after adjusting (incompletely) for some variables etc.
