### ISSUE TITLE
documentation error for function markovBlanket()

### ISSUE THREAD

**Issue by gsverhoeven** [jtextor/dagitty#50]
In: 
https://github.com/jtextor/dagitty/blob/master/r/R/dagitty.r

the help file reads: 

 \code{markovBlanket(x,v}) returns \code{**x**}'s parents, its children, and all other
 parents of its children. The Markov blanket always renders \code{**x**} independent
 of all other nodes in the graph.

x (in bold) should read v. 
x is the input graph, v is the node for which we want the Markov blanket.

**Comment by jtextor** [comment]
Thank you, I fixed it!
