### ISSUE TITLE
markovBlanket() bugs with fix

### ISSUE THREAD

**Issue by behrman** [jtextor/dagitty#58]
Below is some code using dagitty version 0.3-1 and the graph from this [example code](http://dagitty.net/primer/index.html#study-question-2.4.1).

``` r
library(dagitty)

fig_2.9 <- 
  dagitty(
    'dag{
      W -> Y
      X -> W
      Z_1 -> {X Z_3}
      Z_2 -> {Y Z_3}
      Z_3 -> {X Y}
    }'
  )

markovBlanket(fig_2.9, "Z_1")
#> Warning in if (!(v %in% names(x))) stop(paste(v, "is not a variable in `x`")):
#> the condition has length > 1 and only the first element will be used
#> [1] "X"   "Z_3" "Z_2"

markovBlanket(fig_2.9, "Y")
#> Error in if (!(v %in% names(x))) stop(paste(v, "is not a variable in `x`")): argument is of length zero
```

<sup>Created on 2022-03-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The warning and error come from `dagitty:::.checkName()`. The warning is because Z_1 has more than on child. The error is because Y has no children.

The following code fixes these problems.

``` r
library(dagitty)
library(purrr)

fig_2.9 <- 
  dagitty(
    'dag{
      W -> Y
      X -> W
      Z_1 -> {X Z_3}
      Z_2 -> {Y Z_3}
      Z_3 -> {X Y}
    }'
  )

markov_blanket <- function(graph, nodes) {
  map_nodes <- function(nodes, .f) {
    nodes %>% 
      map(.f, x = graph) %>% 
      unlist()
  }
  nodes %>% 
    map_nodes(children) %>% 
    map_nodes(parents) %>% 
    union(nodes %>% map_nodes(parents)) %>% 
    union(nodes %>% map_nodes(children)) %>% 
    setdiff(nodes) %>% 
    sort()
}

markov_blanket(fig_2.9, list())
#> NULL

markov_blanket(fig_2.9, "Z_1")
#> [1] "X"   "Z_2" "Z_3"

markov_blanket(fig_2.9, "Y")
#> [1] "W"   "Z_2" "Z_3"

markov_blanket(fig_2.9, c("W", "Y"))
#> [1] "X"   "Z_2" "Z_3"
```

<sup>Created on 2022-03-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jtextor** [comment]
Thanks for letting me know! I hope it's OK that I didn't use your code, since the underlying issue was in the .kins function, so I fixed that instead. I added your example as a further unit tests and it's working as expected now. Thank you for your contribution!

**Comment by behrman** [comment]
Great. Thanks for the quick fix!
