### ISSUE TITLE
Is there a way to extract all of the covariates rolls for a dag?

### ISSUE THREAD

**Issue by uriahf** [jtextor/dagitty#61]
Hi, thanks for this package!

I wonder if there's a way to extract all of the covariates rolls for a dag.

Ideally, I would like to have a data frame that looks like this:

| Covariate | Roll |
| ----------- | ----------- |
| x | Exposure|
| m   | Mediator|
| w  | Confounder |
| y   | Outcome        |

**Comment by uriahf** [comment]
That's really cool! Does `node_status` supports statuses such as "Collider", "Mediator" and "Confounder"? 

I can iterate over the variables with dagitty::isCollider over the variables, but I'm not familiar with something like isConfounder or isMediator. I wonder if there's a good reason for that or maybe I didn't look well enough

**Comment by malcolmbarrett** [comment]
ggdag also has `node_collider()` and `node_instrumental()` but not the others you mention. "confounder" and "mediator" are a little wishy-washy because they really depend on your research question and analysis.

**Comment by uriahf** [comment]
Thank you, It was really helpful!
