### ISSUE TITLE
Unable to export

### ISSUE THREAD

**Issue by amandacpac** [jtextor/dagitty#76]
Hello, I am trying to export my DAG as a PDF (or any file type, really) and when I do I get the following error:
<img width="659" alt="Screenshot 2023-07-11 at 9 03 15 PM" src="https://github.com/jtextor/dagitty/assets/88414882/6eb3a6c4-a114-413e-937c-b026cc77964f">

If I click "Send Anyway" I just get a blank browser screen. I have tried this on Chrome and Safari, and tried PDF, PNG, JPEG, etc.

**Comment by jtextor** [comment]
I moved the site to https:// yesterday and this part was not working yet. Can you try again? (Perhaps you need to force-reload the browser window)

**Comment by amandacpac** [comment]
I'm still getting the same errors on both chrome and Safari. I've also completely closed both browsers and opened again.

**Comment by jtextor** [comment]
Closing and reopening may not be sufficient, as the browser may still pull the old version from the cache. Try force-reloading (e.g. in Chrome, hold down Shift and click the reload button)

**Comment by amandacpac** [comment]
Oh, I see. That worked. Thank you!
