### ISSUE TITLE
Published DAGs no longer accessible

### ISSUE THREAD

**Issue by mattiaghilardi** [jtextor/dagitty#82]
After the recent webserver migration it is no longer possible to publish new DAGs and to access previously published DAGs using the URL or the `downloadGraph()` function of the R package. Will the old DAGs be transferred to the new server? And will the `Publish on dagitty.net` option under the `Model` menu be made available again?

**Comment by jtextor** [comment]
Hi, all the already published DAGs should be available again. If there is a specific DAG that you can't download, please let me know! With regards to the "Publish" option, I'm currently working to make sure this is implemented in a GDPR-compliant manner.

**Comment by mattiaghilardi** [comment]
Thank you @jtextor, I can confirm that already published DAGs are available again through their URLs. Yet, they can't be downloaded through the `downloadGraph()` function in R. While this breaks some of my previous code, I can easily fix it by directly using the model code. However, I found the function particularly useful and, as you are working on re-implementing the "Publish" option, it would be great to have it working again. If you prefer I could open a separate issue for this.

**Comment by jtextor** [comment]
Hi, thanks for letting me know about the dowloadGraph() function not working anymore. This was using an older API, which I am now mocking on the new server, so it should work again. Can you confirm?

**Comment by mattiaghilardi** [comment]
Hi, I can confirm that the function is working again. Closing it now, thank you!
